export const currency = '$';
export const currentYear = new Date().getFullYear();
export const developedByLink = 'https://mannatthemes.com/';
export const developedBy = 'Mannatthemes';
export const contactUs = 'support@mannatthemes.com';
export const buyLink = '';
export const basePath = '';
export const DEFAULT_PAGE_TITLE = 'Rizz Next | Admin & Dashboard Template';
export const colorVariants = ['primary', 'secondary', 'success', 'warning', 'info', 'danger', 'dark', 'light'];