-- MySQL Script generated by MySQL Workbench
-- Fri Sep 13 10:37:24 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fhd_cinema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fhd_cinema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fhd_cinema` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `fhd_cinema` ;

-- -----------------------------------------------------
-- Table `fhd_cinema`.`ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fhd_cinema`.`ratings` (
  `rating_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT (UUID()),
  `rating_name` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `rating_description` VARCHAR(1000) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`rating_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `fhd_cinema`.`movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fhd_cinema`.`movies` (
  `movie_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT (UUID()),
  `rating_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `movie_title` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `movie_genre` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `movie_director` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `movie_cast` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `movie_status` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `movie_format` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `movie_duration_min` INT UNSIGNED NOT NULL,
  `movie_release_date` DATE NOT NULL,
  `movie_trailer_link` VARCHAR(1000) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `movie_description` VARCHAR(2000) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `movie_banner_text` VARCHAR(1000) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `movie_header_image` VARCHAR(1000) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `movie_poster_image` VARCHAR(1000) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`movie_id`),
  INDEX `fk_movie_ratings1_idx` (`rating_id` ASC) VISIBLE,
  CONSTRAINT `fk_movie_ratings`
    FOREIGN KEY (`rating_id`)
    REFERENCES `fhd_cinema`.`ratings` (`rating_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `fhd_cinema`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fhd_cinema`.`locations` (
  `location_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT (UUID()),
  `location_name` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`location_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `fhd_cinema`.`cinemas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fhd_cinema`.`cinemas` (
  `cinema_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT (UUID()),
  `location_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `cinema_name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`cinema_id`),
  INDEX `fk_cinemas_locations_idx` (`location_id` ASC) VISIBLE,
  CONSTRAINT `fk_cinemas_locations`
    FOREIGN KEY (`location_id`)
    REFERENCES `fhd_cinema`.`locations` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `fhd_cinema`.`screens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fhd_cinema`.`screens` (
  `screen_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT (UUID()),
  `cinema_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `seat_id` VARCHAR(8) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`screen_id`),
  CONSTRAINT `fk_screens_cinemas`
    FOREIGN KEY (`cinema_id`)
    REFERENCES `fhd_cinema`.`cinemas` (`cinema_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `fhd_cinema`.`showtimes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fhd_cinema`.`showtimes` (
  `showtime_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT (UUID()),
  `movie_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `screen_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `showtime_price` INT UNSIGNED NOT NULL,
  `showtime_datetime` DATETIME NOT NULL,
  PRIMARY KEY (`showtime_id`),
  INDEX `fk_showtimes_movie1_idx` (`movie_id` ASC) VISIBLE,
  INDEX `fk_showtimes_screens_idx` (`screen_id` ASC) VISIBLE,
  CONSTRAINT `fk_showtimes_movies`
    FOREIGN KEY (`movie_id`)
    REFERENCES `fhd_cinema`.`movies` (`movie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_showtimes_screens`
    FOREIGN KEY (`screen_id`)
    REFERENCES `fhd_cinema`.`screens` (`screen_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `fhd_cinema`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fhd_cinema`.`accounts` (
  `account_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT (UUID()),
  `account_name` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `customer_email` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `account_type` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`account_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `fhd_cinema`.`memberships`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fhd_cinema`.`memberships` (
  `membership_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT (UUID()),
  `membership_name` VARCHAR(8) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`membership_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `fhd_cinema`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fhd_cinema`.`customers` (
  `customer_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT (UUID()),
  `account_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `membership_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `customer_name` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `customer_email` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `customer_revenue` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`customer_id`),
  INDEX `fk_customers_accounts_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_customers_memberships_idx` (`membership_id` ASC) VISIBLE,
  CONSTRAINT `fk_customers_accounts`
    FOREIGN KEY (`account_id`)
    REFERENCES `fhd_cinema`.`accounts` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customers_memberships`
    FOREIGN KEY (`membership_id`)
    REFERENCES `fhd_cinema`.`memberships` (`membership_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `fhd_cinema`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fhd_cinema`.`bookings` (
  `booking_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT (UUID()),
  `showtime_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `customer_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `booking_price` INT UNSIGNED NOT NULL,
  `create_at` DATETIME NOT NULL,
  PRIMARY KEY (`booking_id`),
  INDEX `fk_bookings_showtimes_idx` (`showtime_id` ASC) VISIBLE,
  INDEX `fk_bookings_customers_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_bookings_showtimes`
    FOREIGN KEY (`showtime_id`)
    REFERENCES `fhd_cinema`.`showtimes` (`showtime_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookings_customers`
    FOREIGN KEY (`customer_id`)
    REFERENCES `fhd_cinema`.`customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `fhd_cinema`.`seats_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fhd_cinema`.`seats_types` (
  `seat_type_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT (UUID()),
  `seat_type_name` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `seat_type_price` INT NULL,
  PRIMARY KEY (`seat_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `fhd_cinema`.`seats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fhd_cinema`.`seats` (
  `seat_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT (UUID()),
  `type_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `screen_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `seat_location` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`seat_id`),
  INDEX `fk_seats_screen_idx` (`screen_id` ASC) VISIBLE,
  INDEX `fk_seats_types_idx` (`type_id` ASC) VISIBLE,
  CONSTRAINT `fk_seats_screen`
    FOREIGN KEY (`screen_id`)
    REFERENCES `fhd_cinema`.`screens` (`screen_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seats_types`
    FOREIGN KEY (`type_id`)
    REFERENCES `fhd_cinema`.`seats_types` (`seat_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `fhd_cinema`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fhd_cinema`.`tickets` (
  `ticket_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT (UUID()),
  `seat_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `booking_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `ticket_price` INT UNSIGNED NOT NULL,
  `create_at` DATETIME NOT NULL,
  PRIMARY KEY (`ticket_id`, `seat_id`),
  INDEX `fk_tickets_bookings_idx` (`booking_id` ASC) VISIBLE,
  INDEX `fk_tickets_seats_idx` (`seat_id` ASC) VISIBLE,
  CONSTRAINT `fk_tickets_bookings`
    FOREIGN KEY (`booking_id`)
    REFERENCES `fhd_cinema`.`bookings` (`booking_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tickets_seats`
    FOREIGN KEY (`seat_id`)
    REFERENCES `fhd_cinema`.`seats` (`seat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `fhd_cinema`.`snacks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fhd_cinema`.`snacks` (
  `snack_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT (UUID()),
  `booking_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `snack_name` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `ticket_price` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`snack_id`),
  INDEX `fk_snacks_bookings_idx` (`booking_id` ASC) VISIBLE,
  CONSTRAINT `fk_snacks_bookings`
    FOREIGN KEY (`booking_id`)
    REFERENCES `fhd_cinema`.`bookings` (`booking_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `fhd_cinema`.`staffs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fhd_cinema`.`staffs` (
  `staff_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT (UUID()),
  `account_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `staff_name` VARCHAR(8) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`staff_id`),
  INDEX `fk_staffs_accounts_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_staffs_accounts`
    FOREIGN KEY (`account_id`)
    REFERENCES `fhd_cinema`.`accounts` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `fhd_cinema`.`vouchers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fhd_cinema`.`vouchers` (
  `voucher_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT (UUID()),
  `membership_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `voucher_discount_percent` INT NOT NULL,
  PRIMARY KEY (`voucher_id`),
  INDEX `fk_vouchers_memberships_idx` (`membership_id` ASC) VISIBLE,
  CONSTRAINT `fk_vouchers_memberships`
    FOREIGN KEY (`membership_id`)
    REFERENCES `fhd_cinema`.`memberships` (`membership_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `fhd_cinema`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fhd_cinema`.`sales` (
  `sale_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT (UUID()),
  `movie_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `cinema_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `sale_revenue` INT NOT NULL,
  PRIMARY KEY (`sale_id`),
  INDEX `fk_sales_cinemas1_idx` (`cinema_id` ASC) VISIBLE,
  INDEX `fk_sales_movies1_idx` (`movie_id` ASC) VISIBLE,
  CONSTRAINT `fk_sales_cinemas1`
    FOREIGN KEY (`cinema_id`)
    REFERENCES `fhd_cinema`.`cinemas` (`cinema_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_movies1`
    FOREIGN KEY (`movie_id`)
    REFERENCES `fhd_cinema`.`movies` (`movie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
